#!/bin/bash
# runs double and single spin analyses, and draws output
root -b -q -l 'Asym3.C('\"sph\"','\"all\"')'
root -b -q -l DrawThree.C
mv -v spin{,_sph}.root
mv -v three{,_sph}.png

root -b -q -l 'Asym3.C('\"pi0\"','\"all\"')'
root -b -q -l DrawThree.C
mv -v spin{,_pi0}.root
mv -v three{,_pi0}.png

root -b -q -l 'Asym3.C('\"thr\"','\"all\"')'
root -b -q -l DrawThree.C
mv -v spin{,_thr}.root
mv -v three{,_thr}.png
