// defines binning that is needed in the analysis
//
// all the binning is controlled by the variables in the section CONTROL VARIABLES
// -- low = lower bound
// -- high = upper bound
// -- bins = number of bins (if zero, manual binning used; see the code below to define these)

void Bin_Splitter()
{
  // CONTROL VARIABLES

  Double_t phi_low=-3.15;
  Double_t phi_high=3.15;
  Int_t phi_bins=1;

  Double_t eta_low=2.5;
  Double_t eta_high=4; // can go up to 4.5, but do we trust the edge data?
  Int_t eta_bins=1;

  Double_t pt_low=0.0;
  Double_t pt_high=15.0; // can go up to 37, but pi0 reconstruction is unreliable for pT>15
  Int_t pt_bins=0;

  Double_t en_low=0.0;
  Double_t en_high=100.0; // can go up to 250, but cluster merging is problem for E>100
  Int_t en_bins=1;

  char efile[64];
  strcpy(efile,"env_bins.sh");

  gSystem->RedirectOutput(efile,"w");
  printf("#!/bin/bash\n");
  printf("# This file was generated by Bin_Splitter.C\n");
  printf("# ** source this file while in this directory\n\n");
  printf("export SPINDIR=$(pwd)\n");


  // phi
  printf("\nexport PHI_LOW=%f\n",phi_low);
  printf("export PHI_HIGH=%f\n",phi_high);
  Double_t phi_width;
  if(phi_bins>0)
  {
    printf("export PHI_BINS=%d\n",phi_bins);
    phi_width = (phi_high-phi_low)/phi_bins;
    for(Int_t i=0; i<=phi_bins; i++) printf("export PHI_DIV_%d=%f\n",i,phi_low+i*phi_width);
  }
  else
  {
    phi_bins=1;
    printf("export PHI_BINS=%d\n",phi_bins);
    printf("export PHI_DIV_0=%f\n",phi_low);
    printf("export PHI_DIV_1=%f\n",phi_high);
  };


  // eta
  printf("\nexport ETA_LOW=%f\n",eta_low);
  printf("export ETA_HIGH=%f\n",eta_high);
  Double_t eta_width;
  if(eta_bins>0)
  {
    printf("export ETA_BINS=%d\n",eta_bins);
    eta_width = (eta_high-eta_low)/eta_bins;
    for(Int_t i=0; i<=eta_bins; i++) printf("export ETA_DIV_%d=%f\n",i,eta_low+i*eta_width);
  }
  else
  {
    eta_bins=1;
    printf("export ETA_BINS=%d\n",eta_bins);
    printf("export ETA_DIV_0=%f\n",eta_low);
    printf("export ETA_DIV_1=%f\n",eta_high);
  };


  // pt
  printf("\nexport PT_LOW=%f\n",pt_low);
  printf("export PT_HIGH=%f\n",pt_high);
  Double_t pt_width;
  if(pt_bins>0)
  {
    printf("export PT_BINS=%d\n",pt_bins);
    pt_width = (pt_high-pt_low)/pt_bins;
    for(Int_t i=0; i<=pt_bins; i++) printf("export PT_DIV_%d=%f\n",i,pt_low+i*pt_width);
  }
  else
  {
    ///*
    // carl's suggestion
    pt_bins=7;
    printf("export PT_BINS=%d\n",pt_bins);
    printf("export PT_DIV_0=%f\n",pt_low);
    printf("export PT_DIV_1=%f\n",1);
    printf("export PT_DIV_2=%f\n",2);
    printf("export PT_DIV_3=%f\n",3);
    printf("export PT_DIV_4=%f\n",4);
    printf("export PT_DIV_5=%f\n",6);
    printf("export PT_DIV_6=%f\n",8);
    printf("export PT_DIV_7=%f\n",pt_high);
    //*/
    /*
    // low vs. high pT
    pt_bins=2;
    printf("export PT_BINS=%d\n",pt_bins);
    printf("export PT_DIV_0=%f\n",pt_low);
    printf("export PT_DIV_1=%f\n",8);
    printf("export PT_DIV_2=%f\n",pt_high);
    */
  };

    
  // en
  printf("\nexport EN_LOW=%f\n",en_low);
  printf("export EN_HIGH=%f\n",en_high);
  Double_t en_width;
  if(en_bins>0)
  {
    printf("export EN_BINS=%d\n",en_bins);
    en_width = (en_high-en_low)/en_bins;
    for(Int_t i=0; i<=en_bins; i++) printf("export EN_DIV_%d=%f\n",i,en_low+i*en_width);
  }
  else
  {
    en_bins=3;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",50);
    printf("export EN_DIV_2=%f\n",100);
    printf("export EN_DIV_3=%f\n",en_high);
  };
  
  gSystem->RedirectOutput(0);
  char cat[128];
  sprintf(cat,".! cat %s",efile);
  printf("\n");
  gROOT->ProcessLine(cat);
  printf("\n%s built; source it by executing\n. env_bins.sh\n",efile);
};
