#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export PHI_LOW=-3.150000
export PHI_HIGH=3.150000
export PHI_BINS=1
export PHI_DIV_0=-3.150000
export PHI_DIV_1=3.150000

export ETA_LOW=2.500000
export ETA_HIGH=4.000000
export ETA_BINS=1
export ETA_DIV_0=2.500000
export ETA_DIV_1=4.000000

export PT_LOW=0.500000
export PT_HIGH=10.000000
export PT_BINS=1
export PT_DIV_0=0.500000
export PT_DIV_1=10.000000

export EN_LOW=0.000000
export EN_HIGH=100.000000
export EN_BINS=7
export EN_DIV_0=0.000000
export EN_DIV_1=15.000000
export EN_DIV_2=25.000000
export EN_DIV_3=35.000000
export EN_DIV_4=50.000000
export EN_DIV_5=65.000000
export EN_DIV_6=80.000000
export EN_DIV_7=100.000000
