#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export PHI_LOW=-3.150000
export PHI_HIGH=3.150000
export PHI_BINS=1
export PHI_DIV_0=-3.150000
export PHI_DIV_1=3.150000

export ETA_LOW=2.500000
export ETA_HIGH=4.000000
export ETA_BINS=1
export ETA_DIV_0=2.500000
export ETA_DIV_1=4.000000

export PT_LOW=2.000000
export PT_HIGH=10.000000
export PT_BINS=1
export PT_DIV_0=2.000000
export PT_DIV_1=10.000000

export EN_LOW=30.000000
export EN_HIGH=100.000000
export EN_BINS=1
export EN_DIV_0=30.000000
export EN_DIV_1=100.000000
