#!/bin/bash
# builds condor batch file for running PatchTrees.C on ../../Output/*.root
# and executes it

job="patch.bat"
> $job

echo "building batch file..."
echo "Executable = `which root`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="logfiles"
wd=$(pwd)
pushd redset > /dev/null
ls *.root > $wd/filelist
popd > /dev/null

#cat filelist
cnt=1

while read line; do
  echo "Arguments = -b -q PatchTrees.C(\\\"${line}\\\")" >> $job
  echo "Log    = ${log}/Patch${cnt}.log" >> $job
  echo "Output = ${log}/Patch${cnt}.out" >> $job
  echo "Error  = ${log}/Patch${cnt}.err" >> $job
  echo "Queue" >> $job
  echo "" >> $job
  let cnt++
done < filelist

njobs=$(grep -c . filelist)
rm filelist
echo "Submitting $njobs jobs to condor"
condor_submit $job
