#!/bin/bash
# builds condor batch file for running PhiDists.C on .redset/*.root
# and executes it

if [ $# -eq 4 ]; then
  phi=$1
  eta=$2
  pt=$3
  en=$4
elif [ $# -ge 1 ]; then
  echo "usage: $0 [phi bins] [eta bins] [pt bins] [en bins]"
  echo " enter either all four arguments or none to use defaults"
  exit 1
else
  phi=16
  eta=1
  pt=3
  en=3
fi


job="phi.bat"
> $job

echo "building batch file..."
echo "Executable = `which root`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="logfiles"
wd=$(pwd)
pushd redset > /dev/null
ls Red*.root > $wd/filelist
popd > /dev/null

#cat filelist
cnt=1

while read line; do
  echo "Arguments = -b -q SinPhiDists.C(\\\"${line}\\\",$phi,$eta,$pt,$en)" >> $job
  echo "Log    = ${log}/Phi${cnt}.log" >> $job
  echo "Output = ${log}/Phi${cnt}.out" >> $job
  echo "Error  = ${log}/Phi${cnt}.err" >> $job
  echo "Queue" >> $job
  echo "" >> $job
  let cnt++
done < filelist

njobs=$(grep -c . filelist)
rm filelist
echo "Submitting $njobs jobs to condor"
condor_submit $job

spin_call="spin_call"
echo "#!/bin/bash" > $spin_call
echo "touch phiset/all.root" >> $spin_call 
echo "rm phiset/all.root" >> $spin_call
echo "hadd phiset/{all,phi*}.root" >> $spin_call
echo "root -b -q 'Spin.C(\"all.root\",$phi,$eta,$pt,$en)'" >> $spin_call
echo ""
echo "execute $spin_call after condor jobs finish"
echo "to call Spin.C with appropriate binning"
