/********************************************************************
* RunDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RunDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRunDataDict();
extern void G__cpp_setup_inheritanceRunDataDict();
extern void G__cpp_setup_typetableRunDataDict();
extern void G__cpp_setup_memvarRunDataDict();
extern void G__cpp_setup_globalRunDataDict();
extern void G__cpp_setup_memfuncRunDataDict();
extern void G__cpp_setup_funcRunDataDict();
extern void G__set_cpp_environmentRunDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RunData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RunDataDictLN_TClass;
extern G__linked_taginfo G__RunDataDictLN_TBuffer;
extern G__linked_taginfo G__RunDataDictLN_TMemberInspector;
extern G__linked_taginfo G__RunDataDictLN_TObject;
extern G__linked_taginfo G__RunDataDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__RunDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RunDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RunDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RunDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RunDataDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__RunDataDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RunDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RunDataDictLN_TTree;
extern G__linked_taginfo G__RunDataDictLN_TFile;
extern G__linked_taginfo G__RunDataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__RunDataDictLN_RunData;

/* STUB derived class for protected member access */
